### ISSUE TITLE
Agent config link is broken

### ISSUE THREAD

**Issue by CapacitorSet** [honeytrap/honeytrap-docs#15]
honeytrap/honeytrap#414:

>the documentation on the honeytrap.io has a 404 on the config-docker.toml file. The docker-compose-honeytrap.yml is ok.

>`wget https://gist.githubusercontent.com/Coen-Schuijt/0600aca75dc99f6c2ce2c260ad00f0ab/raw/config-docker.toml`

>On this page:
https://docs.honeytrap.io/docs/setup/server/setup-prerequisites/

I think it should link to [agent-server](https://github.com/honeytrap/honeytrap-configs/tree/master/agent-server) in the honeytrap-configs repo.

**Comment by jsancho** [comment]
good shout, I've just created a PR with a fix
https://github.com/honeytrap/honeytrap-docs/pull/16

**Comment by AMKuperus** [comment]
We have launced new documentation so this is no longer a issue.
