### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by CapacitorSet** [honeytrap/honeytrap-docs#8]
The docs have a few dead links (found through https://github.com/raviqqe/muffet):

 * `http://docs.honeytrap.io/images/favicon.png` (favicon, linked everywhere)
 * `https://docs.honeytrap.io/docs/concepts/overview/what-is-honeytrap/` (linked from https://docs.honeytrap.io/)
 * `https://docs.honeytrap.io/docs/setup/docker-compose/landing/` and `https://docs.honeytrap.io/docs/setup/go/install-agent/` (linked from https://docs.honeytrap.io/docs/concepts/framework/architecture/)
 * `https://docs.honeytrap.io/docs/setup/sensor/config-firewall.md` (linked from https://docs.honeytrap.io/docs/setup/sensor/setup-prerequisites/)

Finally, all pages link to the Kubernetes license (https://git.k8s.io/website/LICENSE), which probably should be replaced with a direct link to the CC website.

**Comment by Coen-Schuijt** [comment]
Hi CapacitorSet,

Thanks for notifying us. Dead links will be fixed in coming pull request.

**Comment by nl5887** [comment]
Fixed, thanks!
